# Generated by Django 5.2.7 on 2025-10-23 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de Venda')),
                ('estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('imagem', models.ImageField(upload_to='produtos/', verbose_name='Foto do Produto')),
                ('publicado', models.BooleanField(default=False, verbose_name='Disponível no Site')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pagamento Pendente'), ('PAGO', 'Pagamento Confirmado'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pix_cobranca_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Cobrança PIX')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='LogWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
