"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "cCRnpmq9bxcH9fQQ_STL452iI9XTYOYcOaZIaPwN_t0TdI2coe9KgwzBFTtChwGBMtA"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.onrender.com', # Permite todos os subdomínios .onrender.com
    'localhost', # Para testes locais
    '127.0.0.1', # Para testes locais
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "loja",
    "storages",
]
# core/settings.py

# Local onde Django buscará os arquivos estáticos (CSS, JS, imagens do Admin)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# core/settings.py (Adicionar no final)

# Configuração para arquivos de mídia (uploads de usuários, como fotos de produtos)

# Onde os arquivos de mídia serão SALVOS no disco (dentro da pasta media)
MEDIA_ROOT = BASE_DIR / 'media'

# O prefixo da URL para acessar esses arquivos (ex: http://127.0.0.1:8000/media/Azzaro.png)
MEDIA_URL = '/media/'

# Adicione a URL base do seu serviço Render à lista de origens confiáveis
CSRF_TRUSTED_ORIGINS = ['https://projeto-perfumaria-python.onrender.com']

# Se você tiver que adicionar subdomínios, pode usar um wildcard:
# CSRF_TRUSTED_ORIGINS = ['https://*.onrender.com']

# CONFIGURAÇÕES DE COOKIES PARA PRODUÇÃO (Obrigatório em HTTPS/Render)
# Força o uso de cookies de sessão seguros (somente HTTPS).
SESSION_COOKIE_SECURE = True

# Força o uso de cookies de CSRF seguros (somente HTTPS).
CSRF_COOKIE_SECURE = True

# Diz ao Django para confiar nos cabeçalhos 'X-Forwarded-Proto' do Render (HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# settings.py
import os # Já deve estar lá
import dj_database_url # Importar o novo modulo

# ... o restante do seu settings.py

# CONFIGURAÇÃO DE BANCO DE DADOS (USANDO VARIAVEL DE AMBIENTE)
if 'DATABASE_URL' in os.environ:
    # Em produção (Render), usa a variavel DATABASE_URL para PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Localmente (sem a variavel), usa SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
# CONFIGURAÇÕES DO AWS S3 (PARA ARQUIVOS DE MÍDIA)

# Lê variáveis de ambiente do Render
AWS_S3_REGION_NAME = os.environ.get('AWS_REGION_NAME')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')

# Se as variáveis S3 estiverem definidas (ou seja, em producao)
if AWS_STORAGE_BUCKET_NAME: 

    # Define o S3 como o local padrão para upload de arquivos
    DEFAULT_FILE_STORAGE = 'storages.backends.s3.S3Storage'

    # Configurações de acesso e segurança
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'public-read' # Permite que as fotos sejam visíveis

    # Monta o domínio completo para que o Django use para servir as fotos
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

    # A URL que os templates usarão para buscar as fotos
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

else:
    # Configuração de fallback para desenvolvimento local
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
